apiVersion: v1
kind: Namespace
metadata:
  name: java-maven-project-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-deployment
  namespace: java-maven-project-ns
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: javamaven
  template:
    metadata:
      labels:
        app: javamaven
    spec:
      containers:
        - name: java-maven-app-container
          image: agpocacr.azurecr.io/alokeghoshjavacodenaventomcatdockerfile:480
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-svc
  namespace: java-maven-project-ns
  labels:
    service: java-maven-svc
spec:
  type: LoadBalancer
  selector:
    app: javamaven
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
